name       : conmon
version    : 2.0.29
release    : 17
source     :
    - git|https://github.com/containers/conmon : v2.0.29
license    : Apache-2.0
component  : virt
summary    : An OCI container runtime monitor
description: |
    Conmon is a monitoring program and communication tool between a container manager (podman) and an OCI runtime (runc) for a single container.
builddeps  :
    - golang
rundeps    :
    - runc
environment: |
    export PREFIX=%PREFIX%
build      : |
    %make
install    : |
    %make_install
