name       : conmon
version    : 2.0.2
release    : 2
source     :
    - git|https://github.com/containers/conmon : v2.0.2
license    : Apache-2.0
component  : virt
summary    : An OCI container runtime monitor
description: |
    Conmon is a monitoring program and communication tool between a container manager (podman) and an OCI runtime (runc) for a single container.
rundeps    :
    - runc
environment: |
    export PREFIX=%PREFIX%
build      : |
    %make
install    : |
    %make_install
