name       : conmon
version    : 2.0.24
release    : 13
source     :
    - git|https://github.com/containers/conmon : v2.0.24
license    : Apache-2.0
component  : virt
summary    : An OCI container runtime monitor
description: |
    Conmon is a monitoring program and communication tool between a container manager (podman) and an OCI runtime (runc) for a single container.
builddeps  :
    - golang
rundeps    :
    - runc
environment: |
    export PREFIX=%PREFIX%
setup      : |
    %patch -p1 < $pkgfiles/fix_docs_makefile.patch
build      : |
    %make
install    : |
    %make_install
